// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CesiumMap: typeof import('./components/CesiumMap.vue')['default']
    Heatmap: typeof import('./components/Heatmap.vue')['default']
    MapControl: typeof import('./components/MapControl.vue')['default']
    PrimitiveTest: typeof import('./components/PrimitiveTest.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
